version: '3.4'

services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    ports:
      - "80:80"
      - "8080:8080"
    expose:
      - "80"
      - "8080"

  master:
    image: kolibri
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/kolibri-home:/kolibri-home
    environment:
      - EXPLORE_VERSION=master

  stable:
    image: kolibri
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/kolibri-home:/kolibri-home
